services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: geo
      POSTGRES_PASSWORD: geo
      POSTGRES_DB: geo_portal
    ports:
      - "5432:5432"
    volumes:
      - geo_postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  geo_postgres:

